import * as B from './bot.mjs';
const log = (...a) => console.log(new Date().toISOString().slice(11, 19), ...a);
let r = await B.openRound();
log('guess bot2 green', JSON.stringify((await B.pick(2, 'green')).body));
log('guess bot3 red', JSON.stringify((await B.pick(3, 'red')).body));
log('second guess bot3 (must become a credit)', JSON.stringify((await B.pick(3, 'gold')).body));
log('effect tomato bot4', JSON.stringify((await B.fx(4, 'tomato', 5000)).body));
log('effect wrong price (must be rejected)', JSON.stringify((await B.fx(4, 'horn', 1234)).body));
for (let k = 0; k < 2; k++) log('shooting gallery bot5', JSON.stringify((await B.game(5)).body));
const before = { w0: await B.sol(B.addr(0)), w1: await B.sol(B.addr(1)), prize: await B.sol(B.prizeAddr) };
log('fees to fill the balloon'); await B.fee(0.07);
r = await B.waitPhase(['countdown'], 30000); log('countdown started, ends', r.countdown_ends_at);
r = await B.waitPhase(['done', 'drawing'], 60000);
log('sales closed; late burn by bot1 x1 (must become a credit)', JSON.stringify((await B.buy(1, 1, { round: r.id })).body));
r = await B.waitPhase(['done'], 60000);
log('DRAW', 'winner', r.winner_wallet.slice(0, 4), 'tickets', r.winner_tickets, '/', r.draw_total_tickets, 'prize', r.prize_sol, 'last buyer', r.last_buyer?.slice(0, 4), 'mega', r.mega);
await B.sleep(4000);
const pays = await B.rest(`payouts?select=kind,wallet,lamports,status,signature&round_id=eq.${r.id}`); log('payouts', JSON.stringify(pays.map(p => [p.kind, p.wallet.slice(0, 4), p.lamports, p.status, (p.signature || '').slice(0, 6)])));
const after = { w0: await B.sol(B.addr(0)), w1: await B.sol(B.addr(1)), prize: await B.sol(B.prizeAddr) };
log('balances change: bot0', (after.w0 - before.w0).toFixed(5), 'bot1', (after.w1 - before.w1).toFixed(5), 'prize wallet', (after.prize - before.prize).toFixed(5));
const n = (await B.rest('rounds?select=id,balloon,phase,carried_sol&order=id.desc&limit=1'))[0]; log('next round', JSON.stringify(n));
await B.sleep(3000);
log('guesses', JSON.stringify((await B.rest('predictions?select=wallet,color,tickets_if_win,status')).map(p => [p.wallet.slice(0, 4), p.color, p.tickets_if_win, p.status])));
log('tickets round ' + n.id, JSON.stringify((await B.rest(`tickets?select=wallet,count,kind&round_id=eq.${n.id}`)).map(x => [x.wallet.slice(0, 4), x.count, x.kind])));
log('credits left', JSON.stringify((await B.rest('ticket_credits?select=*')).map(x => [x.wallet.slice(0, 4), x.tickets])));
log('effects', JSON.stringify((await B.rest('effects?select=effect,tokens')).map(e => [e.effect, e.tokens])));
